exclude = [
    "gtk-rs-examples",
]

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "warn"
notice = "warn"
ignore = []

[licenses]
unlicensed = "deny"
allow = [
  "MIT",
  "Apache-2.0",
]
copyleft = "deny"
allow-osi-fsf-free = "either"
default = "deny"
confidence-threshold = 0.8

[bans]
multiple-versions = "deny"
wildcards = "allow"
highlight = "all"

# proc-macro-crate depends on an older version of toml_edit
# https://github.com/bkchr/proc-macro-crate/pull/50
[[bans.skip]]
name = "toml_edit"
version = "0.21"
[[bans.skip]]
name = "winnow"
version = "0.5"

# system-deps depends on an old version of heck
# https://github.com/gdesmott/system-deps/pull/88
[[bans.skip]]
name = "heck"
version = "0.4"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
